### ISSUE TITLE
Segmentation fault: 11 when running stats

### ISSUE THREAD

**Issue by marija-kra** [mrvollger/rustybam#1]
Hi, I've been trying to run rustybam stats on a sam file, and I keep getting a 'Segmentation fault: 11' error, and the run is aborted. Initially I thought I might be using too many regions, so I reduced the number down twenty-fold to 66 10 kb fragments and I still get the same issue. 

While I suspect the issue is on my end, I'm wondering if you've come across this issue and is there anything you can suggest to fix it? 

Command: 

rustybam stats ../samfile.sam  > output.txt

Stdout: 

Number of threads: 8
Processing: 82949Segmentation fault: 11

Thanks! Marija

UPDATE: it looks like running it on a sorted bam instead of sam had allowed more alignments to be processed, but it still gave the same seg fault.

**Comment by mrvollger** [comment]
Hi Marija!

If you send me the file or a small file that does segfault I am happy to try and figure out the issue.

From our email the other day I suspect you are trying to make the colored dot plots? If so you might be more interested in this site which I put together over the weekend: https://mrvollger.github.io/StainedGlass/
There have been so many requests that I decided to make some proper instructions / a pipeline.

Best,
Mitchell
