### ISSUE TITLE
There is an error running rb

### ISSUE THREAD

**Issue by IKK1998** [mrvollger/rustybam#10]
Dear Mitchell Robert Vollger,
I really like your rustybam app, but I am currently encountering an error message while using your software rb with the following command:

rb trim-paf input.txt |rb break-paf --max-size 5000 |rb orient |rb filter --paired-len 100000|rb stats --paf >input.for.saffire 
or 
rb trim-paf input.txt

 - Version of rustybam [ v0.1.29 and v0.1.31]
 - linux
[input.txt](https://github.com/mrvollger/rustybam/files/11186934/input.txt)

The error message reads as follows:
thread 'main' panicked at 'assertion failed: t.len() >= 12', src/paf.rs:376:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have previously executed the same command and it produced results. rustybam version is v0.1.29.Additionally, I have also tried running the command with RUST_BACKTRACE=1 and RUST_BACKTRACE=full to obtain more detailed error messages.
Additionally, I would like to know if there are any recommended parameters when using rustybam on plant genomes, or can I use the same parameters as for human genomes? As I am new to bioinformatics, I may have many questions, but your answers are very helpful to me！
I would greatly appreciate any help you can provide in resolving this issue.
Thank you for your time and assistance.
Best regards,
Zukai-Wang

**Comment by mrvollger** [comment]
It looks like the input was generated without `--eqx` from minimap2. can you try with that option.
