### ISSUE TITLE
Support MAF/SAM/PAF/DELTA conversion

### ISSUE THREAD

**Issue by wjwei-handsome** [mrvollger/rustybam#12]
Hi @mrvollger, cool tools!

As the title says, different comparison software like [minimap/mummer/anchorwave] will produce different formats, such as [maf, s/bam, paf, delta].

I noticed that you have implemented the conversion between `paf` and `sam`.

In addition, do you think adding `maf` and `delta` conversion support will make the tool more useful?

If YES, I thinks I could make a PR to complete it.

**Comment by mrvollger** [comment]
Yes I think this could be very useful! Thanks for offering. 

Can you outline which conversions you are thinking of? I think these would be particularly useful:
Delta to PAF
MAF to PAF 

Thanks,
Mitchell

**Comment by mrvollger** [comment]
Any conversion contributions you are interested in making I'd be thrilled to see a PR for. I can imagine lots of use cases. 

A specialized tool also sounds appealing to me, even better if the tool is in rust, and better still if the tool is in rust and has a `lib.rs` in addition to a CLI app. 

Thanks,
Mitchell

**Comment by wjwei-handsome** [comment]
Of course in rust!

Thanks for your proposes:)

I will try to crate a `bin` and `lib`.

Bioinformatic rustaceans are cool!

Wei.

**Comment by wjwei-handsome** [comment]
Hi @mrvollger !

After a period of coding, I developed a corresponding tool and library for the whole genome comparison file crudely.

https://github.com/wjwei-handsome/wgatools

If you have time, can you give me some advice or reference?

Thanks a lot for your proposes!

Best wishes,
Wei

**Comment by mrvollger** [comment]
Hi @wjwei-handsome,

Your repo looks great, and anyone who comes across this issue I recommend you check it out!

In the next ~day I will start a discussion issue in your repo with some of my ideas and thoughts. I'll also update the readme for rustybam to point to your tool or all the extra conversions. 

Thanks!
Mitchell

**Comment by baozg** [comment]
It seems `paf-to-sam` function in `rustybam` didn't work properly. I compare the minimap2 result (paf, sam) and converted sam (from minimap2 paf). The size looks very different and lots of redundant in the sam.

**Comment by mrvollger** [comment]
Please create a new issue with a minimal reproducible example and software versions and I'll look into it.
