### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by hsiehph** [mrvollger/rustybam#7]
Hey Mitchell,

Here is the error I encountered when I used the following command.  I am using rustybam 0.1.29 on linux

$ rustybam liftover --bed <(printf "chrX\t51683493\t51720362\n") chrX.paf | rb invert | rb trim-paf 
Processing contig chrX   1/1  
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/paf.rs:227:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

It seems to me it occurs in the function trim-paf when there is no sequence lifted.  I am including the paf file so you can reproduce the error yourself.

Thanks,
PingHsun(Benson)

[chrX.paf.gz](https://github.com/mrvollger/rustybam/files/9700125/chrX.paf.gz)

**Comment by mrvollger** [comment]
@adadiehl I think that this commit I just pushed fixes this, can you install from source and test your file.

**Comment by adadiehl** [comment]
@mrvollger This seems to have resolved our issue. Thank you!
