### ISSUE TITLE
liftover issues with --qbed flag.

### ISSUE THREAD

**Issue by Xavster838** [mrvollger/rustybam#8]
I'm having trouble using the --qbed flag for liftover. I'm trying to subset a paf file for alignments that contain a particular sequence either in the query or in the target. Subsetting target sequence works fine, but I'm not able to get liftover by passing the same sequence as query.

 - The exact command that produced the error along with the error message:
 `rustybam liftover \
     --bed all_vs_all.bed \
     --qbed <(head -n 1 ${core_dup_bed}) \
     all_vs_all.paf > ${cur_samp}_${cur_hap}_q_all_vs_all.paf`
`error: Found argument 'all_vs_all.paf' which wasn't expected, or isn't valid in this context`

 - A minimal example that reproduces the error including example input files uploaded to github.

 - Version of rustybam: rustybam 0.1.29
 - OS: CentOS7

**Comment by mrvollger** [comment]
--qbed does not accept an argument. It just tells rb that the input bed file has query coordinates and not reference ones. I think the help page explains this but if you find it confusing I'd except a pr with a more detailed explication.
