### ISSUE TITLE
get_fasta not outputting ">" in header names of fasta output

### ISSUE THREAD

**Issue by Xavster838** [mrvollger/rustybam#9]
Hi Mitchell! I'm noticing when I'm running rb get-fasta that the headers in the output fasta are missing the usual ">" start that most tools expect. I'm not sure if this was intentional but it's messing with samtools and other toolkits I try using downstream of this command.

**Comment by Xavster838** [comment]
version: rustybam 0.1.29

**Comment by mrvollger** [comment]
That is not what I had intended. Should be fixed in latest commit, but until I cut a new release you will have to install from main to get the fix.
